### ISSUE TITLE
Mismatch in number of channels for style and content semantic map.

### ISSUE THREAD

**Issue by nylki** [alexjc/neural-doodle#11]
What is the cause of this error? I created a semantic map for both the original and the new semantic map.
All have the same dimensions.

**Comment by alexjc** [comment]
RGB vs RGBA? RGB vs greyscale?

**Comment by nylki** [comment]
@alexjc Thats it. I expected gimp to export no alpha channel, but it did. Thanks for the quick response and the great paper! Will post results later :)

**Comment by alexjc** [comment]
I will add a better error message, leaving this open in the meantime.
