### ISSUE TITLE
ERROR: The optimization diverged and NaN numbers were encountered.

### ISSUE THREAD

**Issue by holyxiaoxin** [alexjc/neural-doodle#14]
I'm currently experiencing the following error:

```
➜  neural-doodle git:(master) ✗ python3 doodle.py --style samples/Monet.jpg --output samples/Coastline.png --device=cpu --iterations=5
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
  - Loading content semantic map from samples/Coastline_sem.png.
  - Loading style image data from samples/Monet.jpg.
  - Loading style semantic map from samples/Monet_sem.png.

Phase #0: resolution 128x96  scale 0.25
  - Style layer sem3_1: 660 patches in 1,538kb.
  - Style layer sem4_1: 140 patches in 648kb.

ERROR: The optimization diverged and NaN numbers were encountered.
  - Try using a different device or change the parameters.
```

**Comment by alexjc** [comment]
What platform? Try the `--safe-mode` argument. Also see #8 for a workaround, inserting `NanGuardMode` for now.

**Comment by ajacksified** [comment]
Same here- late 2013 MBP on OSX 10.10.5, but with `gpu0`. Will try with safe mode and report back.

**Comment by alexjc** [comment]
@ajacksified Ah, in your case it worked but you ran out of memory. I'll try to catch that separately and display a better error!

**Comment by ajacksified** [comment]
Oh, hah. It says "out of memory" right there, I'm just an idiot. No worries, ignore me :D

**Comment by graiz** [comment]
Seeing something similar, running on a Mac.  Using safe mode and CPU. 
 
python3 doodle.py --style samples/Monet.jpg --output samples/Coastline.png  --device=cpu --safe-mode --iterations=2
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
  - Loading content semantic map from samples/Coastline_sem.png.
  - Loading style image data from samples/Monet.jpg.
  - Loading style semantic map from samples/Monet_sem.png.

Phase #0: resolution 128x96  scale 0.25
  - Style layer sem3_1: 660 patches in 1,538kb.
  - Style layer sem4_1: 140 patches in 648kb.

ERROR: The optimization diverged and NaN numbers were encountered.
  - Try using a different device or change the parameters.

**Comment by alexjc** [comment]
@graiz Can you check the last comment of issue #8 and try that?

**Comment by graiz** [comment]
I'm not certain what comment you meant. I tried the patch that imported NanGuardMode.  The last comment referenced mode='FAST_COMPILE' but I wasn't sure what was intended.
