### ISSUE TITLE
Can't install or Unable to find pgen, not compiling formal grammar.

### ISSUE THREAD

**Issue by Ikity** [alexjc/neural-doodle#16]
So i tried installed just like written but at execution of  command

`python3 -m pip install --ignore-installed -r requirements.txt`

> I've got this
> Downloading/unpacking scikit-image>=0.12 (from -r requirements.txt (line 1))
>   Downloading scikit-image-0.12.3.tar.gz (20.7MB): 20.7MB downloaded
>   Running setup.py (path:/home/ikity/Programs/neural-doodle-master/pyvenv/build/scikit-image/setup.py) egg_info for package scikit-image
>     Unable to find pgen, not compiling formal grammar.
>     No eggs found in /tmp/easy_install-f5nxj_yv/Cython-0.23.4/egg-dist-tmp-_odxfti1 (setup script problem?)
>     Traceback (most recent call last):
>       File "<string>", line 17, in <module>
>       File "/home/ikity/Programs/neural-doodle-master/pyvenv/build/scikit-image/setup.py", line 146, in <module>
>         **extra
>       File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 126, in setup
>         dist = setup(**new_attr)
>       File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 169, in setup
>         return old_setup(**new_attr)
>       File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "/usr/lib/python3/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
>         Distribution.__init__(self, attrs)
>       File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/setuptools/dist.py", line 239, in __init__
>         self.fetch_build_eggs(attrs.pop('setup_requires'))
>       File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs
>         replace_conflicting=True
>       File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/pkg_resources.py", line 628, in resolve
>         raise DistributionNotFound(req)
>     pkg_resources.DistributionNotFound: cython>=0.21
>     Complete output from command python setup.py egg_info:
>     Unable to find pgen, not compiling formal grammar.
> 
> No eggs found in /tmp/easy_install-f5nxj_yv/Cython-0.23.4/egg-dist-tmp-_odxfti1 (setup script problem?)
> 
> Traceback (most recent call last):
> 
>   File "<string>", line 17, in <module>
> 
>   File "/home/ikity/Programs/neural-doodle-master/pyvenv/build/scikit-image/setup.py", line 146, in <module>
> 
>     **extra
> 
>   File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 126, in setup
> 
>     dist = setup(**new_attr)
> 
>   File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 169, in setup
> 
>     return old_setup(**new_attr)
> 
>   File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
> 
>     _setup_distribution = dist = klass(attrs)
> 
>   File "/usr/lib/python3/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
> 
>     Distribution.__init__(self, attrs)
> 
>   File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/setuptools/dist.py", line 239, in __init__
> 
>     self.fetch_build_eggs(attrs.pop('setup_requires'))
> 
>   File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs
> 
>     replace_conflicting=True
> 
>   File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/pkg_resources.py", line 628, in resolve
> 
>     raise DistributionNotFound(req)
> 
> pkg_resources.DistributionNotFound: cython>=0.21
> 
> ----------------------------------------
> Cleaning up...
> Command python setup.py egg_info failed with error code 1 in /home/ikity/Programs/neural-doodle-master/pyvenv/build/scikit-image
> Storing debug log for failure in /home/ikity/.pip/pip.log

Any help?

**Comment by alexjc** [comment]
Can you try ``sudo apt-get install cython3``? Or ``python3 -m pip install cython`` in your Virtual Environment?

If that's it I'll update the documentation.

**Comment by Ikity** [comment]
Output of `python3  -m pip install cython` shows

> python3  -m pip install cython
> Requirement already satisfied (use --upgrade to upgrade): cython in /usr/lib/python3/dist-packages
> Cleaning up...

And then it shows the same

> Downloading scikit-image-0.12.3.tar.gz (20.7MB): 20.7MB downloaded
>   Running setup.py (path:/home/ikity/Programs/neural-doodle-master/pyvenv/build/scikit-image/setup.py) egg_info for package scikit-image
>     Unable to find pgen, not compiling formal grammar.
>     No eggs found in /tmp/easy_install-l3bzwfb2/Cython-0.23.4/egg-dist-tmp-nt3wtd8w (setup script problem?)
>     Traceback (most recent call last):
>       File "<string>", line 17, in <module>
>       File "/home/ikity/Programs/neural-doodle-master/pyvenv/build/scikit-image/setup.py", line 146, in <module>
>         **extra
>       File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 126, in setup
>         dist = setup(**new_attr)
>       File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 169, in setup
>         return old_setup(**new_attr)
>       File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "/usr/lib/python3/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
>         Distribution.__init__(self, attrs)
>       File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/setuptools/dist.py", line 239, in __init__
>         self.fetch_build_eggs(attrs.pop('setup_requires'))
>       File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs
>         replace_conflicting=True
>       File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/pkg_resources.py", line 628, in resolve
>         raise DistributionNotFound(req)
>     pkg_resources.DistributionNotFound: cython>=0.21
>     Complete output from command python setup.py egg_info:
>     Unable to find pgen, not compiling formal grammar.
> 
> No eggs found in /tmp/easy_install-l3bzwfb2/Cython-0.23.4/egg-dist-tmp-nt3wtd8w (setup script problem?)
> 
> Traceback (most recent call last):
> 
>   File "<string>", line 17, in <module>
> 
>   File "/home/ikity/Programs/neural-doodle-master/pyvenv/build/scikit-image/setup.py", line 146, in <module>
> 
>     **extra
> 
>   File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 126, in setup
> 
>     dist = setup(**new_attr)
> 
>   File "/usr/lib/python3/dist-packages/numpy/distutils/core.py", line 169, in setup
> 
>     return old_setup(**new_attr)
> 
>   File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
> 
>     _setup_distribution = dist = klass(attrs)
> 
>   File "/usr/lib/python3/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
> 
>     Distribution.__init__(self, attrs)
> 
>   File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/setuptools/dist.py", line 239, in __init__
> 
>     self.fetch_build_eggs(attrs.pop('setup_requires'))
> 
>   File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs
> 
>     replace_conflicting=True
> 
>   File "/home/ikity/Programs/neural-doodle-master/pyvenv/lib/python3.4/site-packages/pkg_resources.py", line 628, in resolve
> 
>     raise DistributionNotFound(req)
> 
> pkg_resources.DistributionNotFound: cython>=0.21
> 
> ----------------------------------------
> Cleaning up...
> Command python setup.py egg_info failed with error code 1 in /home/ikity/Programs/neural-doodle-master/pyvenv/build/scikit-image
> Storing debug log for failure in /home/ikity/.pip/pip.log
>

**Comment by alexjc** [comment]
Are you on Ubuntu? If so, a system install might be best with `apt-get`.

It's not finding the Cython you have installed. `python3 -m pip install --ignore-installed cython`

Related: https://github.com/pypa/pip/issues/2550

**Comment by harshuopi** [comment]
I had the same error.  This solved it.

`sudo apt-get install cython3
`

**Comment by alexjc** [comment]
Great, adding to trouble shooting.
