### ISSUE TITLE
Please make a version with a copyleft license

### ISSUE THREAD

**Issue by torvn77** [alexjc/neural-doodle#19]
Please add the standard compatible copyleft license(GPL ex) which would facilitate the use of your code in large projects, because they need to monitor patent and license cleanliness of the code.
If you don't like copyleft licenses, then take the MIT, Apache or BSD license is the main thing that was accumulated legal experience.
And thank you so much for your work, I hope that soon your program will include such well-known editors gimp, krita or inkscape, or all at once.

Original text:
Пожалуйста добавьте стандартную копилефт совместимую лицензию что бы облегчить применение вашего кода в крупных проектах, так как в них необходимо следить за патентной и лицензионной чистотой кода.
Если вам не нравятся копилефт лицензии, то возьмите MIT, Apache или BSD, главное чтобы лицензия была стандартной с наработанным правовым опытом  использования.
И большое вам спасибо за ваш труд, надеюсь что скоро вашу программу включат в такие известные редакторы gimp, krita или inkscape, ну или во всё сразу.

**Comment by alexjc** [comment]
There is a BSD license already.

**Comment by torvn77** [comment]
I do not understand the license, this when saw the title I decided that you wrote the license themselves.
In General issue is not correct and you can close it. 
I apologize to you for the trouble.
But it is a pity that you have chosen the BSD license, the choice of copyleft licenses in more socially responsible position.

**Comment by cbalint13** [comment]
@torvn77 

* It's @alexjc chioce, nothing wrong with BSD.

**Comment by alexjc** [comment]
Copyleft serves a purpose but not for this project, it doesn't fit my goals. Thanks for your input!
