### ISSUE TITLE
max_pool_2d() got unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by mrzl** [alexjc/neural-doodle#2]
Hi,
this looks interesting, though there were some dependencies missing from the readme, including lasagne, scikit-image, theano and even after resolving these i'm running into problems. i just quickly wanted to check this out, so havent digged deep to resolve this issue myself, but maybe you have an idea what this could be linked to?

```
Phase #0: resolution 128x96  scale 0.25
Traceback (most recent call last):
  File "doodle.py", line 450, in <module>
    generator.run()
  File "doodle.py", line 408, in run
    self.model.setup(layers=['sem'+l for l in self.style_layers] + ['conv'+l for l in self.style_layers])
  File "doodle.py", line 153, in setup
    outputs = lasagne.layers.get_output([self.network[l] for l in layers], self.tensor_inputs)
  File "/root/.venvs/neural-doodle/lib/python3.4/site-packages/lasagne/layers/helper.py", line 185, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/root/.venvs/neural-doodle/lib/python3.4/site-packages/lasagne/layers/pool.py", line 240, in get_output_for
    mode=self.mode,
TypeError: max_pool_2d() got an unexpected keyword argument 'mode'
```

Thanks,
Marcel

**Comment by alexjc** [comment]
You need to grab Theano and Lasagne from the repository, a released version won't do. Did you already have them installed? Did `pip install -r requirements.txt` not work?

**Comment by mrzl** [comment]
My goodness, it must have been late- like that it works nicely.

**Comment by alexjc** [comment]
Glad to hear! ;-)
