### ISSUE TITLE
100% CPU and 5-10GB ram normal when running on GPU?

### ISSUE THREAD

**Issue by mrblubs** [alexjc/neural-doodle#21]
I'm trying to run on my GPU, starting it with `--device gpu0` and it says `'- Using device 'gpu0' for processing the images.'` however it still constantly uses 100% CPU and jumps from 1GB to 10GB ram all the time. Also overall takes very long, usually like 2 hours, much longer than the 10 mins I saw posted a few times. 

Is that normal or is it just not using my GPU despite telling me so?

Specs:
OSX 10.11.3
GPU: 2x 980TI 6GB
CUDA Driver Version: 7.5.25
GPU Driver Version: 10.9.14 (346.03.05f01)

**Comment by alexjc** [comment]
Use `nvidia-smi dmon` to check your graphics card activity. If it works then it must be using the GPU, the slowdown is elsewhere. How big are your images?

**Comment by owenman1** [comment]
I'm using a GTX 960 so I expected it to take longer than ten minutes (and it does). My cpu also maxes out one core the entire time this is running (with --device=gp0). It seems to use gpu memory but doesn't utilise it otherwise, I'm not sure about this. I could be reading the monitor programs incorrectly. 

Here's a screenshot of it running (python3 doodle.py --style samples/Renoir.jpg --output samples/Landscape.png                   --device=gpu0 --iterations=40)
![screenshot from 2016-03-12 18-52-54](https://cloud.githubusercontent.com/assets/17802874/13724955/1a0eeb20-e88d-11e5-9d4c-aaf108c3fd7e.png)

**Comment by alexjc** [comment]
The `91` and `41` in the fourth column indicate that your GPU is used, just not very often. How big are your images? Is this for the examples provided?

**Comment by owenman1** [comment]
This is using the Renoir.jpg Landscape_sem.png samples.

The command executed was: ```python3 doodle.py --style samples/Renoir.jpg --output samples/Landscape.png --device=gpu0 --iterations=40```

**Comment by alexjc** [comment]
Hmm, is it swapping? I don't see `kswapd` in your top. I'm not sure about this, it's not normal I have to think about how to approach it.

**Comment by alexjc** [comment]
It should look like in `nvidia-smi dmon` this when running on GPU correctly:
```
# gpu   pwr  temp    sm   mem   enc   dec  mclk  pclk
# Idx     W     C     %     %     %     %   MHz   MHz
    0    88    63    50    25     0     0  3004  1252
    0    60    63     0     1     0     0  3004  1252
    0    75    63    19     9     0     0  3004  1252
    0    59    63     0     1     0     0  3004  1240
    0    62    63    16     3     0     0  3004  1240
    0    63    64     2     1     0     0  3004  1252
    0    66    63    26     4     0     0  3004  1252
    0    65    64    22     2     0     0  3004  1252
    0    72    64    37     5     0     0  3004  1252
    0    67    64    42     5     0     0  3004  1252
    0    75    64    21     4     0     0  3004  1252
    0    70    65    67    14     0     0  3004  1252
    0    80    65    11     2     0     0  3004  1252
    0    74    65    79    17     0     0  3004  1252
    0    79    64     0     1     0     0  3004  1252
    0    83    65    49    10     0     0  3004  1252
    0    77    64    19     3     0     0  3004  1252
    0   100    66    81    18     0     0  3004  124
```

It doesn't use more than 25% of the memory for the 512x320 resolution, but regularly uses >33% of compute. You can run multiple images in parallel too.

If there's a problem getting to this level of utilization, then it's either swapping, CPU is really slow, or it's being locked by something else somehow.  Are your NVIDIA drivers up-to-date? Do you have `cudnn`?
