### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kinazarov** [alexjc/neural-doodle#22]
Collecting Theano==0.8-dev from git+https://github.com/Theano/Theano.git@e7f6b32#egg=Theano==0.8-dev (from -r requirements.txt (line 2))
  Cloning https://github.com/Theano/Theano.git (to e7f6b32) to /tmp/pip-build-tt531toy/Theano
  Could not find a tag or branch 'e7f6b32', assuming commit.
Collecting Lasagne==0.2-dev from git+https://github.com/Lasagne/Lasagne.git@664b8a4#egg=Lasagne==0.2-dev (from -r requirements.txt (line 3))
  Cloning https://github.com/Lasagne/Lasagne.git (to 664b8a4) to /tmp/pip-build-tt531toy/Lasagne
  Could not find a tag or branch '664b8a4', assuming commit.
  Requested Lasagne==0.2-dev from **git+https://github.com/Lasagne/Lasagne.git@664b8a4#egg=Lasagne==0.2-dev (from -r requirements.txt (line 3)), but installing version None**

**Comment by alexjc** [comment]
Is there anything else? These may just be log messages and nothing harmless.

**Comment by kinazarov** [comment]
It says that there is no such branch of Lasagne and does not install it.

**Comment by alexjc** [comment]
Update PIP with `python3 -m pip install --ignore-installed pip`?

**Comment by kinazarov** [comment]
Yes.
Just following your instructions as they written

**Comment by alexjc** [comment]
Maybe you have older versions of PIP. Install Lasagne from the Git master otherwise.

**Comment by kinazarov** [comment]
Now scipy/setup.py does not run properly :(

**Comment by kinazarov** [comment]
error: library dfftpack has Fortran sources but no Fortran compiler found

**Comment by kinazarov** [comment]
All setup scripts worked

But now I got ths error


Traceback (most recent call last):
  File "doodle.py", line 68, in <module>
    import scipy.optimize
  File "/home/konst/python-doodle/pyvenv/lib/python3.5/site-packages/scipy/optimize/__init__.py", line 233, in <module>
    from ._minimize import *
  File "/home/konst/python-doodle/pyvenv/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 30, in <module>
    from .lbfgsb import _minimize_lbfgsb
  File "/home/konst/python-doodle/pyvenv/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 44, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/home/konst/python-doodle/pyvenv/lib/python3.5/site-packages/scipy/sparse/linalg/__init__.py", line 113, in <module>
    from .dsolve import *
  File "/home/konst/python-doodle/pyvenv/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/__init__.py", line 60, in <module>
    from .linsolve import *
  File "/home/konst/python-doodle/pyvenv/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 10, in <module>
    from . import _superlu
ImportError: /home/konst/python-doodle/pyvenv/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/_superlu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: dtrsm_

**Comment by alexjc** [comment]
In general, that's why I recommend using your system (e.g. `apt`) to install numpy or scipy. It prevents these issues as the maintainer takes care of binaries & dependencies.

**Comment by kinazarov** [comment]
It is how I did it already.

**Comment by alexjc** [comment]
Something is very broken in your system-level installation, I'm not sure what, but symbols from binary libraries are not found as expected.

`import scipy.optimize` should work on its own from Python.

**Comment by alexjc** [comment]
If you have any more information about this, let me know!

**Comment by kinazarov** [comment]
Updated my system and it all works fine now
