### ISSUE TITLE
'NoneType' object has no attribute 'shape' erorr with custom style sample

### ISSUE THREAD

**Issue by koniahin** [alexjc/neural-doodle#23]
Hello.
I am try to use neural-doodle with custom style image data and get error:
```
(pyvenv) [anton@laptop neural-doodle]$ python3 doodle.py --style samples/Bilibin_1.jpg --output samples/Custom.png --device=cpu --iterations=60
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
  - Loading content semantic map from samples/Custom_sem.png.
  - Loading style image data from samples/Bilibin_1.jpg.
Traceback (most recent call last):
  File "doodle.py", line 487, in <module>
    generator = NeuralGenerator()
  File "doodle.py", line 228, in __init__
    if self.content_map_original.shape[2] != self.style_map_original.shape[2]:
AttributeError: 'NoneType' object has no attribute 'shape'
```
If I change `--style` to  `samples/Monet.jpg`  all work fine and I get result picture.
I am use Fedora 23 and python 3.4.3
This is link to [style sample](https://cloud.githubusercontent.com/assets/6325570/13722353/961e28b4-e853-11e5-91fc-6173930d94cd.jpg). I am try few different image and every time get this eror.

**Comment by alexjc** [comment]
Looks like `samples/Bilibin_1_sem.png` is missing or not loaded? I'll add a better error message.

**Comment by koniahin** [comment]
Yes, you right. I am sorry, missing this moment. I think what only `output` need `*_sem` file. Now all right, thanks.

**Comment by alexjc** [comment]
Going to leave this open until I fix the error message.

**Comment by 96102313** [comment]
This is a reopened  issue
