### ISSUE TITLE
Style copy error

### ISSUE THREAD

**Issue by bmaltais** [alexjc/neural-doodle#24]
Hi,

Great work by the way. I really like what you are doing!

I am trying to do the copy style instead of the doodle but I always get this error when running the command:

python3 doodle.py --style samples/forpaint4512.jpg --output samples/for1ores.png --device=gpu0 --content samples/for1o.png
Neural Doodle for semantic style transfer.
  - Using device `gpu0` for processing the images.
  - Loading content image data from samples/for1o.png.
  - Loading style image data from samples/forpaint4512.jpg.
Traceback (most recent call last):
  File "doodle.py", line 488, in <module>
    generator = NeuralGenerator()
  File "doodle.py", line 229, in __init__
    if self.content_map_original.shape[2] != self.style_map_original.shape[2]:
AttributeError: 'NoneType' object has no attribute 'shape'

Any idea as to what I am doing wrong? I have deleted the _sem.png files also.

**Comment by bmaltais** [comment]
I think the issue is with:

        if self.content_map_original is None:
            print("\n{}INFO: No content map detected")
            self.content_map_original = np.zeros(self.content_img_original.shape[:2]+(1,))
            self.semantic_weight = 0.0

but I am not sure how to fix it ;-(

**Comment by alexjc** [comment]
I pushed a few fixes to catch errors better. Did you try the very latest? Can you paste the log so I can see which files are loaded?

**Comment by bmaltais** [comment]
Same thing with latest update. The doodle aspect with sem.PNG work fine. But does not if the style copy without sem.PNG files. I thing the issue is that there is no shape attributs in the content_map_original object. Might be an initialisation to zero issue?

**Comment by alexjc** [comment]
Can you try now? #42 may have been the problem and fixed.

**Comment by bmaltais** [comment]
Working great. I am kicking myself for missing the initialization. I could have fixed it yesterday ;-)

It is working just fine right now. I am comparing results from style-transfer, neural-doodle and neural-doodle style copy at the moment. I will post a link to a google doc containing the results. It is very interesting so far.

**Comment by bmaltais** [comment]
Here is the link to the result and how I obtained them: https://docs.google.com/document/d/1OurIXrimTr2KKHznDiQ1oafUSghC_2WtT8EEjxm7Ei8/edit?usp=sharing
