### ISSUE TITLE
Tool for Easy Creation of `_sem` Images

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [alexjc/neural-doodle#25]
Hi, great project.
I wanted to use Python 2.7 and ended up modifying few lines / pickle. 
https://github.com/AKSHAYUBHAT/Art/tree/master/neural-doodle
It seems to work fine. 

I also saw that you need _sem images, I plan to incorporate an annotation UI I have built for other project, that uses superpixels to quickly label individual pixels images. 
https://github.com/AKSHAYUBHAT/ImageSegmentation
![screenshot 2016-03-12 08 59 12](https://cloud.githubusercontent.com/assets/35259/13723374/d2cc5a7e-e830-11e5-96fb-9d0c748264e8.png)

**Comment by alexjc** [comment]
Very cool. Someone tried KMeans too, with some success. I'm planning to look into segmentation more once I get back from GDC.

**Comment by rayset** [comment]
could you explain me how do you use this pickle instead of the default one?

If we manage to run it with python2 we may have opencl support.

**Comment by AKSHAYUBHAT** [comment]
@rayset download this (https://www.dropbox.com/s/sa94i9dwaq3yah2/data.pickle.gz?dl=0) pickle and you can then use it with python2 by replacing line 151 to 
`data = pickle.load(file("data.pickle")) `
you can see other changes here https://github.com/AKSHAYUBHAT/Art/blob/master/neural-doodle/doodle.py

**Comment by alexjc** [comment]
@rayset Which OpenCL library supports Python 2 only? I think there are a couple changes required now, not just one line.
