### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by legnar** [alexjc/neural-doodle#41]
Hi.
I have Python 3.5.1, Windows 7 (SP1). This is what happens for me:

> python3 -m pip install -r requirements.txt 

Requirement already satisfied (use --upgrade to upgrade): scikit-image>=0.12 in c:\python35\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Theano==0.8-dev from git+https://github.com/Theano/Theano.git@e7f6b32#egg=Theano==0.8-dev in c:\python35\lib\site-packages (from -r requirements.txt (line 2))
Collecting Lasagne==0.2-dev from git+https://github.com/Lasagne/Lasagne.git@664b8a4#egg=Lasagne==0.2-dev (from -r requirements.txt (line 3))
  Cloning https://github.com/Lasagne/Lasagne.git (to 664b8a4) to c:\users\michal\appdata\local\temp\pip-build-140pbzi_\lasagne
Requirement already satisfied (use --upgrade to upgrade): dask[array]>=0.5.0 in c:\python35\lib\site-packages (from scikit-image>=0.12->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): networkx>=1.8 in c:\python35\lib\site-packages (from scikit-image>=0.12->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pillow>=2.1.0 in c:\python35\lib\site-packages (from scikit-image>=0.12->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.3 in c:\python35\lib\site-packages (from scikit-image>=0.12->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in c:\python35\lib\site-packages (from Theano==0.8-dev->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.11 in c:\python35\lib\site-packages (from Theano==0.8-dev->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): toolz>=0.7.2 in c:\python35\lib\site-packages (from dask[array]>=0.5.0->scikit-image>=0.12->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in c:\python35\lib\site-packages (from networkx>=1.8->scikit-image>=0.12->-r requirements.txt (line 1))
Installing collected packages: Lasagne
  Found existing installation: Lasagne 0.2.dev1
    Uninstalling Lasagne-0.2.dev1:
      Successfully uninstalled Lasagne-0.2.dev1
  Running setup.py install for Lasagne: started
    Running setup.py install for Lasagne: finished with status 'done'
Successfully installed Lasagne-0.2.dev1

> python3 doodle.py --style samples/Monet.jpg --output samples/Coastline.png --device=cpu --iterations=40

<-[l;36mNeural Doodle for semantic style transfer.«-[0m Traceback <most recent call last>:
File ’'doodle .py”, line 68, in <module>
import scipy.optimize
File ’'C:\Python35\lib\site-packages\scipy\optimize\	init	.py”, line 232, in
<module>
from .optimize import *
File ’'C:\Pytbon35\lib\site-packages\scipy\optimize\optimize.py’', line 37, in < module>
from .linesearch import <line_search_wolfel, line_search_wolfe2.
File ’'C:\Python35\lib\site-packages\scipy\optimize\linesearch.py’', line 18, in <module>
from scipy.optimize import minpack2 ImportError: DLL load failed: Nie można odnaleźć określonego modułu.

**Comment by alexjc** [comment]
Did you inistall `scipy` from Anaconda or Miniconda?
