### ISSUE TITLE
Exception within exception

### ISSUE THREAD

**Issue by oiale** [alexjc/neural-doodle#44]
Phase #1: resolution 649x406  scale 0.5
  - Style layer sem3_1: 16280 patches in 38,095kb.
  - Style layer sem4_1: 3942 patches in 18,306kb.

 60   error 1.03e+04   style 3_1 2.73e+03  4_1 7.61e+03   quality 5.0% 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: MaxAndArgmax, argmax failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "doodle.py", line 503, in <module>
    generator.run()
  File "doodle.py", line 488, in run
    iprint=-1)                       # Handle our own logging of information.
  File "/usr/local/lib/python3.4/dist-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/usr/local/lib/python3.4/dist-packages/scipy/optimize/lbfgsb.py", line 330, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/local/lib/python3.4/dist-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/usr/local/lib/python3.4/dist-packages/scipy/optimize/optimize.py", line 289, in function_wrapper
    return function(*(wrapper_args + args))
  File "/usr/local/lib/python3.4/dist-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "doodle.py", line 407, in evaluate
    grads, *losses = self.compute_grad_and_losses(current_img, self.content_map)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: MaxAndArgmax, argmax failed
Apply node that caused the error: MaxAndArgmax(Elemwise{Composite{((i0 / i1) / i2)}}[(0, 0)].0, TensorConstant{(1,) of 0})
Toposort index: 178
Inputs types: [TensorType(float32, matrix), TensorType(int64, (True,))]
Inputs shapes: [(16280, 15840), (1,)]
Inputs strides: [(63360, 4), (8,)]
Inputs values: ['not shown', array([0])]
Outputs clients: [[], [AdvancedSubtensor(W, argmax, SliceConstant{None, -4, None})]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "doodle.py", line 503, in <module>
    generator.run()
  File "doodle.py", line 463, in run
    self.prepare_optimization()
  File "doodle.py", line 325, in prepare_optimization
    self.losses = self.content_loss() + self.style_loss() + self.total_variation_loss()
  File "doodle.py", line 379, in style_loss
    best = dist.argmax(axis=0)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

-----------------------------------------------------
Not sure what to do

**Comment by alexjc** [comment]
How much memory do you have? Does it fit into memory? I have some separate optimizations coming up that should help with it.

If that's the problem, the bug seems to be that it's not returning a MemoryError more clearly.

**Comment by oiale** [comment]
I have 4 GB of memory, and I think that was the problem. I ran script that did free -m every 10 seconds, and here are last ~2 minutes of output:
----------------
20:11:56
             total       used       free     shared    buffers     cached
Mem:          3806       1653       2153          7         35        460
-/+ buffers/cache:       1158       2648
Swap:            0          0          0
------------------------------------------------------
 
20:12:06
             total       used       free     shared    buffers     cached
Mem:          3806       1652       2154          7         35        460
-/+ buffers/cache:       1156       2649
Swap:            0          0          0
------------------------------------------------------
 
20:12:16
             total       used       free     shared    buffers     cached
Mem:          3806       1777       2028          7         35        460
-/+ buffers/cache:       1282       2524
Swap:            0          0          0
------------------------------------------------------
 
20:12:26
             total       used       free     shared    buffers     cached
Mem:          3806       1651       2155          7         35        460
-/+ buffers/cache:       1156       2650
Swap:            0          0          0
------------------------------------------------------
 
20:12:36
             total       used       free     shared    buffers     cached
Mem:          3806       1652       2154          7         35        460
-/+ buffers/cache:       1156       2650
Swap:            0          0          0
------------------------------------------------------
 
20:12:46
             total       used       free     shared    buffers     cached
Mem:          3806       1834       1972          7         35        460
-/+ buffers/cache:       1338       2468
Swap:            0          0          0
------------------------------------------------------
 
20:12:56
             total       used       free     shared    buffers     cached
Mem:          3806       1696       2110          7         35        460
-/+ buffers/cache:       1201       2605
Swap:            0          0          0
------------------------------------------------------
 
20:13:06
             total       used       free     shared    buffers     cached
Mem:          3806       3649        157          7         15        306
-/+ buffers/cache:       3327        479
Swap:            0          0          0
------------------------------------------------------
 
20:13:16
             total       used       free     shared    buffers     cached
Mem:          3806       3650        156          7         16        306
-/+ buffers/cache:       3327        479
Swap:            0          0          0
------------------------------------------------------
 
20:13:26
             total       used       free     shared    buffers     cached
Mem:          3806       3650        156          7         16        306
-/+ buffers/cache:       3327        479
Swap:            0          0          0
------------------------------------------------------
 
20:13:36
             total       used       free     shared    buffers     cached
Mem:          3806       3650        156          7         16        306
-/+ buffers/cache:       3327        479
Swap:            0          0          0
------------------------------------------------------
 
20:13:46
             total       used       free     shared    buffers     cached
Mem:          3806       3224        582          7         16        308
-/+ buffers/cache:       2900        906
Swap:            0          0          0
------------------------------------------------------

It suddenly consumed about 2 gb of memory. Could it be a leak ? If not, is there a way to reduce memory consumption? Otherwise, it will be hard to render pictures above 600x600.

Also, a question regarding the algorithm:
Will the script work correctly if I give it semantic map as a picture itself? For example : 
python3 doodle.py --style samples/autumn.jpg --output samples/output.png \
                  --device=cpu --iterations=40
where output_sem.png is not the semantic map of a picture, but a picture itself. It is more like I want to take a photograph and make it look like it was drawn by one of the artists.

**Comment by alexjc** [comment]
The underlying does garbage collection of the GPU memory and it's very good. It's unlikely there's a leak. Extra allocation could come from another version of the script, or your X Window manager?

Can you post that other question separately in a new thread? It's a long answer.
