### ISSUE TITLE
Ubuntu additional packages

### ISSUE THREAD

**Issue by orloffm** [alexjc/neural-doodle#48]
Hi. I compiled this list of commands needed to prepare the environment (for CPU runs) on Ubuntu 14 64b. Please use it if you find it useful.

	sudo apt-get update
	sudo apt-get upgrade
	sudo apt-get install git python3.4-venv python3-numpy python3-scipy build-essential libjpeg-dev zlib1g-dev python3-dev python3-setuptools liblapack-dev gfortran
	export OMP_NUM_THREADS=8
	mkdir neural-doodle
	git clone https://github.com/alexjc/neural-doodle.git neural-doodle
	cd neural-doodle
	source pyvenv/bin/activate
	python3 -m pip install pip --upgrade
	python3 -m pip install cython --upgrade
	wget https://github.com/alexjc/neural-doodle/releases/download/v0.0/vgg19_conv.pkl.bz2

**Comment by bmaltais** [comment]
Thank you for the post. I also had to install the following before being able to install the dependencies:

sudo apt-get install libfreetype6-dev
python3 -m pip install --ignore-installed -r requirements.txt

So for me in the end it was:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git python3.4-venv python3-numpy python3-scipy build-essential libjpeg-dev zlib1g-dev python3-dev python3-setuptools liblapack-dev gfortran
export OMP_NUM_THREADS=8
cd ~
git clone https://github.com/alexjc/neural-doodle.git neural-doodle
cd neural-doodle
source pyvenv/bin/activate
python3 -m pip install pip --upgrade
python3 -m pip install cython --upgrade
sudo apt-get install libfreetype6-dev
python3 -m pip install --ignore-installed -r requirements.txt
wget https://github.com/alexjc/neural-doodle/releases/download/v0.0/vgg19_conv.pkl.bz2

**Comment by bmaltais** [comment]
To use nvidia cuda I also had to do:

sudo ldconfig /usr/local/cuda/lib64

**Comment by alexjc** [comment]
We now have scripts in `docker*.df` and the `docker` folder that contain the full reproducible installation scripts.
