### ISSUE TITLE
Threaded operation

### ISSUE THREAD

**Issue by FruitieX** [alexjc/neural-doodle#5]
Is there any easy way to run the program in multithreaded mode when running on the cpu? This should bring a massive speedup to people without NVIDIA cards.

**Comment by alexjc** [comment]
You can set the environment variable `OMP_NUM_THREADS=4` before launching the application to enable threading in theory. In practice, I've found that it doesn't give any speedups on my machine—still not entirely sure why. It's possible those types of operations parallelize poorly with the CPU code.

http://deeplearning.net/software/theano/tutorial/multi_cores.html

**Comment by alexjc** [comment]
Added to the README, but it shows no performance improvement.
