### ISSUE TITLE
Proposed change

### ISSUE THREAD

**Issue by bmaltais** [alexjc/neural-doodle#52]
I changed the setup_model(self) section to the following and it appear to produce slightly sharper and more detailed image:

    def setup_model(self):
        """Use lasagne to create a network of convolution layers, first using VGG19 as the framework
        and then adding augmentations for Semantic Style Transfer.
        """

        net = {}

        # First network for the main image. These are convolution only, and stop at layer 4_2 (rest unused).
        net['img']     = InputLayer((1, 3, None, None))
        net['conv1_1'] = ConvLayer(net['img'],   64, 3, pad=1)
        net['conv1_2'] = ConvLayer(net['conv1_1'], 64, 3, pad=1)
        net['pool1']   = PoolLayer(net['conv1_2'], 2, mode='average_exc_pad')
        net['conv2_1'] = ConvLayer(net['pool1'],   128, 3, pad=1)
        net['conv2_2'] = ConvLayer(net['conv2_1'], 128, 3, pad=1)
        net['pool2']   = PoolLayer(net['conv2_2'], 2, mode='average_exc_pad')
        net['conv3_1'] = ConvLayer(net['pool2'],   256, 3, pad=1)
        net['conv3_2'] = ConvLayer(net['conv3_1'], 256, 3, pad=1)
        net['conv3_3'] = ConvLayer(net['conv3_2'], 256, 3, pad=1)
        net['conv3_4'] = ConvLayer(net['conv3_3'], 256, 3, pad=1)
        net['pool3']   = PoolLayer(net['conv3_4'], 2, mode='average_exc_pad')
        net['conv4_1'] = ConvLayer(net['pool3'],   512, 3, pad=1)
        net['conv4_2'] = ConvLayer(net['conv4_1'], 512, 3, pad=1)
        net['main']    = net['conv4_2']

        # Second network for the semantic layers.  This dynamically downsamples the map and concatenates it.
        net['map'] = InputLayer((1, 3, None, None))
        net['map_1'] = PoolLayer(net['map'], 1, mode='average_exc_pad') 
        net['map_2'] = PoolLayer(net['map'], 2, mode='average_exc_pad')
        net['map_3'] = PoolLayer(net['map'], 4, mode='average_exc_pad')
        net['map_4'] = PoolLayer(net['map'], 8, mode='average_exc_pad')

        net['sem1_1'] = ConcatLayer([net['conv1_1'], net['map_1']])
        net['sem2_1'] = ConcatLayer([net['conv2_1'], net['map_2']])
        net['sem3_1'] = ConcatLayer([net['conv3_1'], net['map_3']])
        net['sem4_1'] = ConcatLayer([net['conv4_1'], net['map_4']])

        # Third network for the nearest neighbors; it's a default size for now, updated once we know more.
        net['nn1_1'] = ConvLayer(net['sem1_1'], 1, 3, b=None, pad=0)
        net['nn2_1'] = ConvLayer(net['sem2_1'], 1, 3, b=None, pad=0)
        net['nn3_1'] = ConvLayer(net['sem3_1'], 1, 3, b=None, pad=0)
        net['nn4_1'] = ConvLayer(net['sem4_1'], 1, 3, b=None, pad=0)

        self.network = net

Let me know what you think.

**Comment by alexjc** [comment]
Do you have some screenshots of the difference? In general, this approach does not scale well as images or number of patches grow, but I'm curious to see! (I only have 4Gb here and using 1_1 and 2_1 makes it run out of memory fast.)

**Comment by bmaltais** [comment]
Look at the very last page of https://docs.google.com/document/d/1OurIXrimTr2KKHznDiQ1oafUSghC_2WtT8EEjxm7Ei8/edit?usp=sharing

You can see more details in the largest leaf (bottom center) and all over the place in general... But I agree, it is marginal.

I also have 4GB GTX780 in my mac and can run it just fine.

**Comment by alexjc** [comment]
Your images look great! As long as 3_1 and 4_1 remain the default (for now), I'm fine with adding those extra layers in the code that can be enabled by users. Feel free to submit a PR ;-)

**Comment by alexjc** [comment]
Oh, I also noticed your semantic maps for the flowers used colors that are similar to the original image. Currently it's best to use "normalized" colors (like pure R, G or B) so try it to see if you get better results. I may add some auto-normalization code.
