### ISSUE TITLE
Amazon AWS ami-981715f2 (West Virginia Region)

### ISSUE THREAD

**Issue by ladyka** [alexjc/neural-doodle#54]
I can't complete step
python3 -m pip install --ignore-installed -r requirements.txt

https://gist.github.com/ladyka/757dd67e3189096f8aab

Can you write step-by-step manual for clear system, example ubuntu 14.04?

**Comment by bmaltais** [comment]
Try those steps for ubuntu:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git python3.4-venv python3-numpy python3-scipy build-essential libjpeg-dev zlib1g-dev python3-dev python3-setuptools liblapack-dev gfortran
export OMP_NUM_THREADS=8
cd ~
git clone https://github.com/alexjc/neural-doodle.git neural-doodle
cd neural-doodle
source pyvenv/bin/activate
python3 -m pip install pip --upgrade
python3 -m pip install cython --upgrade
sudo apt-get install libfreetype6-dev
python3 -m pip install --ignore-installed -r requirements.txt
wget https://github.com/alexjc/neural-doodle/releases/download/v0.0/vgg19_conv.pkl.bz2

Good luck

**Comment by DataRogue** [comment]
I'm failing on the second to last step. 

It's cloning them into some temporary pip build bundle, but it's also not properly getting the sci-image package. That's in addition to it failing on freetype, but I assume that's what the previous line is for. 

I'm using an AWS Ubuntu ami if it makes any difference. Speaking of AMIs, is there any chance we can get a public ami for this available to deploy on the g2 AWS machines? Given that most people might not have an nvidia GPU and a primary linux dev environment, but don't want to wait for hours for an output.

**Comment by bmaltais** [comment]
I am working on one. I will post a link to the AMI later.

**Comment by bmaltais** [comment]
OK, try this AMI with a g2.2xlarge spot request VM: ami-981715f2

**Comment by DataRogue** [comment]
Thanks mate.

Just as a heads up, AMIs are not shared across server centers, so this one is only at the N. Virginia server center.

**Comment by ProGamerGov** [comment]
@bmaltais Your AMI seems to have some issues at the moment: https://github.com/alexjc/neural-doodle/issues/84

**Comment by alexjc** [comment]
@ProGamerGov The Docker image will be the recommended approach from now on. It's very new but should be updated automatically.

**Comment by ProGamerGov** [comment]
@alexjc The docker version does not appear to be working: https://github.com/alexjc/neural-doodle/issues/104
