### ISSUE TITLE
is the editor in the gif just a mock up? how do I generate the _sem masks?

### ISSUE THREAD

**Issue by rayset** [alexjc/neural-doodle#55]
I'm talking about this one: https://github.com/alexjc/neural-doodle/blob/master/docs/Workflow.gif

is there a software to paint and automatically use it as a source for the doodling?

I also have a problem figuring out how to generate the _sem files for the styles. Monet_sem, seth_sem all look amazing, were they done by hand? is there some clever way to syntetize them?

**Comment by bmaltais** [comment]
It is called GIMP. There are tons of filters you can use to create masks. Have fun.

Gimp is like Photoshop but free ;-)

**Comment by bmaltais** [comment]
P.S., _sem are just images saved as PNG. They don't have to be... it is just what Alex selected to use as a file format. JPG will also work if you change the command line options.

**Comment by rayset** [comment]
oh wow, that was gimp... 
what filter do you use to make your masks? I don't remember any filter like this in photoshop: 
![gogh_sem](https://cloud.githubusercontent.com/assets/9410263/13865326/7bf00af6-ecaa-11e5-96d7-f572783c70bf.png)

**Comment by bmaltais** [comment]
Well, try g'mic filters (google for them). There is one under coutour that allow you to easilly select part of images. You then paint color over the mask created. You have to manually repeat for each area. 

Look at https://www.youtube.com/watch?v=ujQHSCsT12g or https://www.youtube.com/watch?v=JfxTTU4yba8 for some examples.

**Comment by rayset** [comment]
thank you! the fact that they made a gift where it seems to be a program like ''click here to apply filter'' is a bit triky.

if someone knows how they did the interpolation (or ''transformation'') between the doodle and the end result I'd like to know. I think generating a gif like that with my results would be even more awesome.

I did it with CNNMRF since it saves all the iterations as different files, but I don't see this option in neural doodle.

**Comment by bmaltais** [comment]
Some example I made using masks I made in gimp:

https://twitter.com/netputing/status/710129796332687360
https://twitter.com/netputing/status/710119813847207937

More details at https://t.co/MW384jdiYL

**Comment by rayset** [comment]
oh my, some in that google docs are insane, you are very good.

do you use the foreground extractor for the masks?
