### ISSUE TITLE
Request for source images on paper

### ISSUE THREAD

**Issue by fallcolor1002** [alexjc/neural-doodle#56]
Hi, could you also provide the source image pairs and their corresponding semantic maps in Fig. 2 on your paper? Thanks a lot!

**Comment by alexjc** [comment]
Yes, I will put them into samples soon. Just re-rendered the Gogh ones and the results are actually better than in the paper! Will try with Figure 2 as well.

**Comment by alexjc** [comment]
I made some changes to the portraits from the renders in the pre-print to make them compatible with Gogh and Seth. Current code seems to handle them better. I will re-render them for the paper once the review is over.

**Comment by alexjc** [comment]
Here are the two renders of the images that are in the repository. First is the success case, works almost as in the paper. Second is the failure case, a bit worse than in the paper (I removed some smaller annotations to make it compatible with Seth and Gogh).

![freddieasmia](https://cloud.githubusercontent.com/assets/445208/14580215/db23c93a-03c6-11e6-952c-d015d79fbe6f.png)
![miaasfreddie](https://cloud.githubusercontent.com/assets/445208/14580216/dd791096-03c6-11e6-9918-2d05fd50a531.png)
