### ISSUE TITLE
Docker Images for AWS and Azure

### ISSUE THREAD

**Issue by toksaitov** [alexjc/neural-doodle#61]
Hi,

I was struggling and wasting too much time installing and setting up all dependencies on spot AWS GPU g2.2xlarge instances between regions and on different Azure machines, so I've decided to create Docker images to ease up the deployment on Ubuntu 14.04. 

If anybody is interested, you can find instructions, Docker files, scripts to install host dependencies, and, of course, images here

For a CPU setup
[github.com/toksaitov/neural-doodle-cpu](http://github.com/toksaitov/neural-doodle-cpu)
For a GPU CUDA setup
[github.com/toksaitov/neural-doodle-gpu](http://github.com/toksaitov/neural-doodle-gpu)
Images on Docker Hub
[hub.docker.com/r/toksaitov/neural-doodle](https://hub.docker.com/r/toksaitov/neural-doodle)

With NVIDIA Docker (with GPU drivers) installed on the host experimenting with the project could be as easy as running

    nvidia-docker run --interactive --tty --volume="$(pwd)/data":/data/ toksaitov/neural-doodle:gpu --style=/data/Style.png --output=/data/Result.png --iterations=160

If you don't want to use GPU acceleration, you just need to install Docker on the host and use it directly

    docker run --interactive --tty --volume="$(pwd)/data":/data/ toksaitov/neural-doodle:cpu --style=/data/Style.png --output=/data/Result.png --iterations=160

Currently the builds are not automatic, but it will be resolved in a week or two.

**Comment by IndeedPlusPlus** [comment]
The image should be rebuilt every time this repo changes.
see toksaitov/neural-doodle-gpu#1

**Comment by alexjc** [comment]
@IndeedPlusPlus I'd be glad if you looked into it! Never done this before.

**Comment by IndeedPlusPlus** [comment]
Hello, here are the steps.

## @toksaitov the image maintainer's steps
_Or of course if you fork the repo and create your own image, these steps become yours._
1. Go to the image page on Docker Hub https://hub.docker.com/r/toksaitov/neural-doodle/
2. Click on **Build Settings** tab
3. Look for **Build Triggers** panel at the end of the page, click **Activate Triggers** button.
4. Now you get a url in **Trigger URL**, send the url to you somehow (via email for example)

## your side
1. Go to GitHub, find this repo
2. Click **Settings** tab
3. Click **Add Webhook**
4. GitHub will ask you which events you would like to trigger this webhook, choose **Let me select individual events.** and check only push
5. Paste url from the image maintainer to **Payload URL**
6. Click **Add webhook** at the end of page and you are good to go

**Comment by alexjc** [comment]
@IndeedPlusPlus Many thanks! I'll probably merge it all into this repository so the trigger works correctly, what do you think?

**Comment by IndeedPlusPlus** [comment]
IMO maybe it would be easier to merge docker related files to this repo.

**Comment by IndeedPlusPlus** [comment]
forked. now I am working on it
