### ISSUE TITLE
Proposed improvements to doodle.py

### ISSUE THREAD

**Issue by bmaltais** [alexjc/neural-doodle#64]
I have modified the doodle.py app to allow many more combinations. Have a look and give it a try. I think it could make sens to add those to provide more flexibility in the future.

[doodle.py.zip](https://github.com/alexjc/neural-doodle/files/190572/doodle.py.zip)

Example of a commend to use it:

python3 doodle.py --style ../in/vg/srcl.jpg --output ../in/vg/dst.jpg  --device=gpu0 --save-every 10 --style-layers=3_1,4_1,5_1 --semantic-ext='-m2.png' --seed=content --content-layer=3_2,4_2,5_2

I also added time to the frames output so they are not constantly over written. This is good to compare and monitor progress.

**Comment by alexjc** [comment]
What do you mean by "combinations"? You can make a GitHub PR if you want, that's a good place to comment on code with the GitHub tools.

**Comment by alexjc** [comment]
Also, if/when you make a Pull Request, make one separate PR for each conceptual feature (e.g. filename changes, layer extensions).

**Comment by bmaltais** [comment]
By combination I mean having the ability to use style of 5_4 or 5_2. The current version only allow styles at the 1st layers like 3_1, 4_1 and does not allow 5_x. The modified version allow all possible selections and combo. Memory is the limit. I would really like to tap into the 2_x styles but it take way to much memory. Perhaps if there was a way to reduce the patch # for levels to reduce memory.

I will try the pull request. Not sure how to do it but I should be able to figure it out ;-)

**Comment by bmaltais** [comment]
OK. I created a pull request. So made a mistake and included three proposed changes in one pull request. I guess I should have created a branch for each? Anyway, they are quite usefull I thing:

1. Save interim files in the directory where the final image will be saved. Make more sense than a separate frames directory.
2. Add many more styles and convolutions options
3. Add a size option to resize the desired output on the fly without having to size every files 1st.

Bernard
