### ISSUE TITLE
Memory problems again.

### ISSUE THREAD

**Issue by Hellsy22** [alexjc/neural-doodle#70]
Before lastest two updates (7 and 8 days ago) I was able to use GPU for 600x600 images (2G).
Now limit is ~450x450. Is it ok or bug?

**Comment by alexjc** [comment]
The code has changed a bit, it's higher quality but I didn't realize it required that much more memory. I'll see what can be done to address this.

I suggest you use the older version if you don't mind that quality for now.

**Comment by alexjc** [comment]
Oh, it just occurred to me that this may be due to including layers `conv4_3` all the way to `conv5_4` now. I would have thought they get ignored, but maybe not... Can you try removing them and setting `net['main'] = net['conv4_2']`?

**Comment by alexjc** [comment]
New code supports better memory usage with `--slices`. Set it to a higher number to reduce the size of each batch.
