### ISSUE TITLE
Setting up nvcc for running on GPU.

### ISSUE THREAD

**Issue by Hallr841** [alexjc/neural-doodle#73]
OSError: You forced the use of gpu device 'gpu0', but nvcc was not found. Set it in your PATH environment variable or set the Theano flags 'cuda.root' to its directory

**Comment by alexjc** [comment]
To setup the GPU you need to go through CUDA setup procedures.
https://github.com/Lasagne/Lasagne/wiki/From-Zero-to-Lasagne

**Comment by Hallr841** [comment]
it don't work at first, then I add the vgg19 unzip to the file  and it started to work with the cpu

**Comment by alexjc** [comment]
I added all documentation for Linux and Windows into the README, closing this.
