### ISSUE TITLE
Installation Issue - Error when installing dependencies via pip module

### ISSUE THREAD

**Issue by crazyrumer** [alexjc/neural-doodle#81]
Hi,

I booted the fresh 14.04 Ubuntu, then followed Linux installation of Lasagne guide. I think I did itcorrectly, at least when I run the BLAS test it shows that thing is running on GPU and it takes 2 seconds.

Then I pulled repo into my workspace folder.
Then run 
python3 -m venv pyvenv --system-site-packages in my temp folder
then run
source pyvenv/bin/activate

and then went back to neuro-doodle folder and ran this command
(pyvenv) tima@home:~/Workspace/neural-doodle$ python3 -m pip install --ignore-installed -r requirements.txt

it failed with error

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/tima/Workspace/temp/pyvenv/build/matplotlib
Storing debug log for failure in /home/tima/.pip/pip.log

Attaching pip.log below
[piplog.txt](https://github.com/alexjc/neural-doodle/files/243853/piplog.txt)

**Comment by alexjc** [comment]
From the error message, it seems you need to install `freetype` and `png` libraries. I think there's another Issue here with full `apt` install instructions, try that and see if it works?

**Comment by crazyrumer** [comment]
i managed to get freetype and png installed, so these errors are gone but then got hit with
missing library
/usr/bin/ld: cannot find -lcblas
[piplog.txt](https://github.com/alexjc/neural-doodle/files/243868/piplog.txt)

**Comment by alexjc** [comment]
You need `python3-dev`, it's listed in the installation instructions but not very obvious. I'll update this...

**Comment by crazyrumer** [comment]
Did it this morning, fixed the error above, still comes with an error, will provide more info after getting back to my Linux machine.

**Comment by alexjc** [comment]
What tutorial are you following? Did you see the link to Lasagne's installation?

**Comment by crazyrumer** [comment]
yeh I followed [that](https://github.com/Lasagne/Lasagne/wiki/From-Zero-to-Lasagne-on-Ubuntu-14.04) and run all the tests fine,cude OpenBlas etc, the problem started when running requirements.


(pyvenv) tima@home:~/Workspace/neural-doodle$ python3 -m pip install --ignore-installed -r requirements.txt

it seems like I was missing like 10 things(freetype, png, svnsomething, bunch of libraries, etc). I am just going through errors and searching them online and asking for help here when I am stuck. Can't post my latest one, away from my Linux machine.

I think when I am done. I will do clean install again of ubuntu and all other stuff on separate hard drive and see where I went wrong. I am not linux or python user and never used Theano or Lasagne before, so I was expecting to run into a lot of problems, just from lack of understanding what I am doing.

Thanks for timely support. Artists are very keen to try the tool, when I actually manage to install it.

**Comment by alexjc** [comment]
The easiest way to install is to use the Docker image, which should already be setup. I'll see if I can improve the instructions for that...

**Comment by crazyrumer** [comment]
[piplog.txt](https://github.com/alexjc/neural-doodle/files/245992/piplog.txt)

I am pretty sure cython is missing I tried to install via your instruction on the website and via http://stackoverflow.com/questions/35096281/cython-setup-error-unable-to-find-pgen-not-compiling-formal-grammar

but still gives the same error

I will try docker image next time around. Too far down the rabbit hole to give up.

**Comment by alexjc** [comment]
Maybe this? https://github.com/alexjc/neural-doodle#cant-install-or-unable-to-find-pgen-not-compiling-formal-grammar

**Comment by crazyrumer** [comment]
I did it first. Didn't work. Will try again this evening.

**Comment by crazyrumer** [comment]
[piplog.txt](https://github.com/alexjc/neural-doodle/files/245992/piplog.txt)

I am pretty sure cython is missing I tried to install via your instruction on the website and via http://stackoverflow.com/questions/35096281/cython-setup-error-unable-to-find-pgen-not-compiling-formal-grammar

but still gives the same error

I will try docker image next time around. Too far down the rabbit hole to give up.
