### ISSUE TITLE
ImportError: No module named 'skimage'

### ISSUE THREAD

**Issue by ProGamerGov** [alexjc/neural-doodle#84]
```
ubuntu@ip-Address:~/neural-doodle$ python3 doodle.py --style samples/Renoir.jpg --output samples/Landscape.png --device=gpu0 --iterations=8
Neural Doodle for semantic style transfer.
Traceback (most recent call last):
  File "doodle.py", line 69, in <module>
    import skimage.transform
ImportError: No module named 'skimage'
ubuntu@ip-Address:~/neural-doodle$
```

How do I fix this?

I was using this Amazon AMI: http://thecloudmarket.com/image/ami-981715f2--neural-doodle-stylehttp://thecloudmarket.com/image/ami-981715f2--neural-doodle-style

ami-981715f2

**Comment by ikarth** [comment]
It's not finding scikit-image. Try: `pip3 install scikit-image`

Though missing that may mean you're missing other prerequisites that you'll also need to add.

**Comment by ProGamerGov** [comment]
@ikarth I was trying to use an AMI to more easily setup and use Neural Doodle.

**Comment by alexjc** [comment]
It's possible this image is older and that dependency is missing? The docker image is more recent (yesterday) but work in progress!

**Comment by alexjc** [comment]
Closing this and also closing the original AMI thread (no longer updated).
