### ISSUE TITLE
Help mounting host folders within Docker instance

### ISSUE THREAD

**Issue by alexjc** [alexjc/neural-doodle#86]
The docker container for CPU execution works well, but I can't easily mount folders to use inside: for example `samples` and `frames`. I'd like to map these to a local folder on my host easily so I can see the output in Finder/Explorer without having to mess with volumes.

Is there an easy way to do this? Feel free to update the README.rst (with PR) or post here so I can do it.

Thanks!

**Comment by shul** [comment]
http://stackoverflow.com/questions/23439126/how-to-mount-host-directory-in-docker-container

**Comment by minimaxir** [comment]
It might not be possible to automount host directories outside of the docker command at runtime. [see [discussion on Docker](https://github.com/docker/docker/issues/3156)]

Using the previous Docker container what I do at runtime is something like this: (assuming my files at located at `~/data`)

```
docker run --interactive --tty --volume="$(pwd)/data":/data/ --volume="$(pwd)/data/frames":/neural-doodle/frames/ toksaitov/neural-doodle:cpu --style=/data/sketch.jpg --content=/data/MaxFBGrey.png --output=/data/test.png --iterations=250 --print-every=1 --save-every=1 --style-weight=20.0 --phases=1
```

**Comment by IndeedPlusPlus** [comment]
I don't get it. Isn't volumes suitable for your case? Are you using boot2docker or having some trouble with docker volumes? AFAIK the volumes work well on my Linux host with nvidia-docker.

**Comment by alexjc** [comment]
My previous `-v` arguments didn't work because it was relative path, and it became a volume not a mounted folder. I need to test if the version with `$(pwd)` actually works as expected.

Volumes are OK as long as they are minimal hassle.
